apiVersion: v1
kind: Service
metadata:
  name: sample-node-app
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '3000'
spec:
  selector: 
    app: sample-node-app
  ports:
    - port: 8080
      targetPort: 8080
      name: hello